### ISSUE TITLE
Inline Tweaks do not work on Xcode 8 / iOS 10

### ISSUE THREAD

**Issue by coreyfloyd** [facebook/Tweaks#109]
It appears that the inline macros are no longer storing the data in mach-o. So none of the tweaks registered with Macros are being loaded at run time.

I'm not very familiar with mach-o, so I'm not sure how to fix it. Does anyone have any ideas on how to go about it?

**Comment by grp** [comment]
Is this only on device, or also in the iOS 10 simulator? I don't have Xcode 8 downloaded yet, but can probably grab it soon if it's in the simulator too.

You could try adding some logging to see how far it gets towards loading the tweaks. The tweaks are loaded in this file: https://github.com/facebook/Tweaks/blob/master/FBTweak/FBTweakInline.m Depending on how far it makes it in the loop, that will isolate where the issue is.

**Comment by bryanboyko** [comment]
I've also noticed this happening and I'm on XCode 7.3.1 and iOS 9.3.2.  The issue appears to be becuase of the pod version and not the XCode or device version. (I've been testing with 'Tweaks', '~> 2.0')

I noticed that the Tweaks example project was working fine and compared the difference in implementation between FBTweakInline.m in the example project and version 2.0 from pods. In the file from pods, in method + (void)load, section is NULL

```
  const fb_tweak_section *section = fb_tweak_getsectbynamefromheader((void *)mach_header, FBTweakSegmentName, FBTweakSectionName);
  
  if (section == NULL) {
    return;
  }
```

Replacing the code in FBTweakInline.m from the pod with code from the same file in the example projects solves the issue

**Comment by grp** [comment]
Ah, this is probably because you're using dynamic frameworks, and support for that as only adde din a895274d5ed5ecf7aa2296a9d840dec2dca4f1a5. @b3ll / @nlutsenko, maybe time for a new release with that commit?

**Comment by coreyfloyd** [comment]
@grp ahhh… we did change to frameworks… thats probably the issue. I'll check that out and verify it fixes the issue.

**Comment by grp** [comment]
Using #101 to track this.
